global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'wiki'
    static_configs:
      - targets: ['wiki:3000']
#  - job_name: 'nginx'
#    static_configs:
#      - targets: ['nginx:80']      
